### ISSUE TITLE
Show master status 错误

### ISSUE THREAD

**Issue by 129duckflew** [zhuchao941/canal2sql#11]
数据库版本 : MySQL8.4
jdk: 21

运行脚本: 
```bash
java -jar .\canal2sql-1.1.3.jar -mode online -u root -p 12345678 -P 9000 -h 192.168.103.30

```
连接出现报错 提示是 show master status命令有错误

```html
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error!
Caused by: java.io.IOException: ErrorPacket [errorNumber=1064, fieldCount=-1, message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1, sqlState=42000, sqlStateMarker=#]
 with command: show master status
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61) ~[canal.parse.driver-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:107) ~[canal.parse-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPosition(MysqlEventParser.java:663) ~[canal.parse-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:380) ~[canal.parse-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:438) ~[canal.parse-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:357) ~[canal.parse-1.1.5.jar!/:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.5.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
# totally cost:19629 ms


````

**Comment by zhuchao941** [comment]
你去你的mysql实例上执行下`show master status`试下看

**Comment by zhuchao941** [comment]
我看了下 8.4.0 把这个命令删了
![image](https://github.com/user-attachments/assets/c67dc97e-35cb-4ac7-9ebc-da2876cc18e9)
那不好意思 暂时不支持了这里

**Comment by 129duckflew** [comment]
> 我看了下 8.4.0 把这个命令删了 ![image](https://private-user-images.githubusercontent.com/9283968/356168336-c67dc97e-35cb-4ac7-9ebc-da2876cc18e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU3MTIsIm5iZiI6MTcyMzExNTQxMiwicGF0aCI6Ii85MjgzOTY4LzM1NjE2ODMzNi1jNjdkYzk3ZS0zNWNiLTRhYzctOWViYy1kYTI4NzZjYzE4ZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTExMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI1OTFiYjY4ZmFkMTVhZjc0ZTQ5NjA4OGQwYTNhNjQ2MDFmYjQ4OGY2NmY1OGYwYjA1OTM5YTI1MWI0ZThjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2WD3qySf25GAuX-8fSWpXngwGriCk45a4jfC82lm7dw) 那不好意思 暂时不支持了这里

8.4 改成 show binary status了
