### ISSUE TITLE
离线模式解析有问题

### ISSUE THREAD

**Issue by ahang1598** [zhuchao941/canal2sql#6]
17:11:45.376 [destination = null , address = localhost/127.0.0.1:3306 , EventParser] ERROR c.g.z.c.parser.BinlogFileEventParser - dump address localhost/127.0.0.1:3306 has an error, retrying. caused by
java.net.MalformedURLException: no protocol: 'file:C://Users//xxx//Downloads//mysql-bin.009848'
        at java.net.URL.<init>(URL.java:611) ~[na:1.8.0_372]
        at java.net.URL.<init>(URL.java:508) ~[na:1.8.0_372]
        at java.net.URL.<init>(URL.java:457) ~[na:1.8.0_372]
        at com.github.zhuchao941.canal2sql.fetcher.BinlogFileLogFetcher.open(BinlogFileLogFetcher.java:63) ~[classes!/:1.1.2]
        at com.github.zhuchao941.canal2sql.connection.BinlogFileConnection.dump(BinlogFileConnection.java:68) ~[classes!/:1.1.2]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262) ~[canal.parse-1.1.5.jar!/:na]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
# totally cost:1754 ms

java -jar canal2sql-1.1.2.jar -mode file -ddl ddl.sql -file_url 'file:C://Users//xxx//Downloads//mysql-bin.009848'

**Comment by zhuchao941** [comment]
看起来是url没给对，试试file://C://Users//xxx//Downloads//mysql-bin.009848 @ahang1598

**Comment by singi2016cn** [comment]
`window`下目录这么写可以正常运行:
```
-file_url 'file:G:/binlog/mysql-bin.0000001'
```

**Comment by JiangRunqiang** [comment]
windows下一些字符串配置是双引号可以通过的
java -jar ./canal2sql-1.1.3.jar -mode file  -file_url "file:C:\ProgramData\MySQL\MySQL Server 8.1\Data\RUNQIANG-bin.000008"  -uroot -proot -P3306 -hlocalhost -filter data.ti_check_result_info -start_time "2024-09-06 14:00:00" -end_time "2024-09-06 15:00:00"

**Comment by dmanbu** [comment]
> 看起来是url没给对，试试file://C://Users//xxx//Downloads//mysql-bin.009848 @ahang1598

linux下，该怎么写呢？file:///home/user/mysql-bin.000016 和 file:/home/user/mysql-bin.000016 都不行
